apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookweb-postgresql
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookweb-postgresql
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: postgres
        image: postgres:9.6.5
        env:
        - name: POSTGRES_USER
          value: bookweb
        - name: POSTGRES_PASSWORD
          value:
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/
---
apiVersion: v1
kind: Service
metadata:
  name: bookweb-postgresql
  namespace: default
spec:
  selector:
    app: bookweb-postgresql
  ports:
  - port: 5432
